services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ecommerce_test
      TZ: Asia/Shanghai
    ports:
       - "3306:3306"
    volumes:
       - mysql8-data:/var/lib/mysql
    command:
       - --character-set-server=utf8mb4
       - --collation-server=utf8mb4_unicode_ci
       - --default-time-zone=+08:00
       - --innodb-buffer-pool-size=2G
       - --innodb-flush-log-at-trx-commit=2

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    restart: unless-stopped
    volumes:
      - ./conf/mysql_exporter.cnf.example:/etc/my.cnf
    command:
      - --config.my-cnf=/etc/my.cnf
      - --collect.info_schema.processlist
      - --collect.engine_innodb_status
      - --web.listen-address=:9104
    ports:
      - "9104:9104"
    depends_on:
      - mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./conf/grafana-datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
    ports:
      - "3000:3000"

  

volumes:
  mysql8-data:
  prometheus-data:
  grafana-data:
